In [1]:
#Import Library

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
#adding the Dataset

In [4]:
dataset=pd.read_csv("Social_Network_Ads.csv")

In [5]:
dataset

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [6]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [7]:
dataset

      User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [8]:
#Splite input & Out put data set

In [9]:
dataset.columns

Index(['User ID', 'Age', 'EstimatedSalary', 'Purchased', 'Gender_Male'], dtype='object')

In [10]:
independant=dataset[['User ID', 'Age', 'EstimatedSalary', 'Gender_Male']]

In [11]:
independant

      User ID  Age  EstimatedSalary  Gender_Male
0    15624510   19            19000            1
1    15810944   35            20000            1
2    15668575   26            43000            0
3    15603246   27            57000            0
4    15804002   19            76000            1
..        ...  ...              ...          ...
395  15691863   46            41000            0
396  15706071   51            23000            1
397  15654296   50            20000            0
398  15755018   36            33000            1
399  15594041   49            36000            0

[400 rows x 4 columns]

In [12]:
dependant=dataset[["Purchased"]]

In [13]:
dependant

     Purchased
0            0
1            0
2            0
3            0
4            0
..         ...
395          1
396          1
397          1
398          0
399          1

[400 rows x 1 columns]

In [14]:
dataset[["Purchased"]].value_counts()

Purchased
0            257
1            143
Name: count, dtype: int64

In [15]:
# split the Train set & test set dataset

In [16]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test =train_test_split(independant,dependant,test_size=1/3,random_state=0)

In [17]:
X_train

      User ID  Age  EstimatedSalary  Gender_Male
218  15666675   46            96000            0
101  15593014   28            59000            1
311  15622585   39            96000            1
194  15689751   28            89000            1
326  15713463   41            72000            1
..        ...  ...              ...          ...
323  15619465   48            30000            0
192  15779581   29            43000            1
117  15591433   36            52000            1
47   15776348   27            54000            0
172  15794661   26           118000            0

[266 rows x 4 columns]

In [18]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [19]:
X_test

array([[ 0.50438342, -0.76605872,  0.52531653,  1.00754728],
       [-0.5437953 ,  0.02298918, -0.57354963, -0.99250926],
       [ 1.23670637, -0.27290378,  0.16892751,  1.00754728],
       [ 0.68734969, -0.76605872,  0.28772385, -0.99250926],
       [-0.74978259, -0.27290378, -0.57354963, -0.99250926],
       [ 1.76837878, -1.06195168, -1.4645222 ,  1.00754728],
       [-1.14843675, -0.66742773, -1.61301763, -0.99250926],
       [-0.14050546, -0.1742728 ,  2.21816441,  1.00754728],
       [-0.34719383, -1.94963056, -0.03896609, -0.99250926],
       [-0.97190892,  0.91066806, -0.78144323,  1.00754728],
       [-0.01405442, -0.76605872, -0.60324872,  1.00754728],
       [ 1.56888716, -0.96332069, -0.42505421, -0.99250926],
       [ 1.18810327, -0.07564181, -0.42505421,  1.00754728],
       [-1.59094386,  0.12162016,  0.22832568,  1.00754728],
       [ 0.79738986, -1.75236858,  0.49561745,  1.00754728],
       [ 1.41218974, -0.56879674,  1.4162891 , -0.99250926],
       [ 1.00386361, -0.07564181,  0.22832568,  1.00754728],
       [ 1.68117363, -1.85099957,  0.46591836,  1.00754728],
       [-0.51761229,  1.69971595,  1.80237721, -0.99250926],
       [ 0.25497239, -0.27290378, -1.40512403,  1.00754728],
       [-1.15540458, -0.27290378, -0.66264689, -0.99250926],
       [ 0.79830555,  0.91066806,  2.21816441, -0.99250926],
       [-0.17511568,  0.31888214, -0.54385055, -0.99250926],
       [ 0.56516233,  0.91066806,  1.05990007,  1.00754728],
       [-1.08719999, -1.45647562, -1.22692951, -0.99250926],
       [ 0.90787356,  1.10793003,  2.12906715, -0.99250926],
       [-0.33111203, -0.96332069,  0.52531653, -0.99250926],
       [ 0.10414111, -0.8646897 ,  0.31742293,  1.00754728],
       [-0.84897755, -0.07564181, -0.21716061, -0.99250926],
       [-1.51464115, -0.56879674,  0.49561745, -0.99250926],
       [-1.47932986, -1.6537376 ,  0.55501562,  1.00754728],
       [-0.75564873, -0.07564181,  0.28772385,  1.00754728],
       [ 1.77623368,  1.89697793, -0.27655878,  1.00754728],
       [-0.97630137, -0.07564181, -0.48445238,  1.00754728],
       [ 0.39580263, -1.35784464, -0.33595695,  1.00754728],
       [ 0.80594583, -1.94963056, -0.51415146,  1.00754728],
       [-0.08021301, -1.55510661,  0.34712202,  1.00754728],
       [-1.55600457, -0.37153477, -0.78144323, -0.99250926],
       [-0.24380672, -0.66742773, -1.048735  , -0.99250926],
       [-1.37877567,  1.10793003, -0.98933683, -0.99250926],
       [ 1.08568908, -1.06195168,  0.55501562,  1.00754728],
       [-0.23001414,  0.31888214, -0.51415146,  1.00754728],
       [-1.32150213, -1.06195168,  0.43621927, -0.99250926],
       [ 1.72459736, -0.27290378, -1.4645222 ,  1.00754728],
       [ 0.21305097,  0.51614411,  1.26779367, -0.99250926],
       [-0.50801186, -1.06195168, -0.33595695, -0.99250926],
       [ 1.48059463, -0.07564181,  0.31742293, -0.99250926],
       [ 0.85343294,  1.40382299,  0.61441379, -0.99250926],
       [ 1.03297968, -1.16058266, -1.16753134,  1.00754728],
       [-1.09053367,  1.10793003,  0.49561745,  1.00754728],
       [ 1.21876457,  1.89697793,  1.56478452, -0.99250926],
       [-0.9668297 , -0.37153477, -1.31602677, -0.99250926],
       [-1.77011861, -0.27290378, -0.36565603, -0.99250926],
       [-1.70941124, -0.37153477,  1.35689093,  1.00754728],
       [-1.15517565,  2.0942399 ,  0.55501562, -0.99250926],
       [ 0.74108924,  0.71340608, -1.10813317,  1.00754728],
       [ 0.77993452, -0.8646897 ,  0.40652019, -0.99250926],
       [-1.71174338, -1.16058266,  0.31742293, -0.99250926],
       [ 1.46525683,  1.10793003, -1.22692951,  1.00754728],
       [-0.73155464, -1.45647562, -1.4645222 ,  1.00754728],
       [-1.39542977, -0.56879674, -1.52392037,  1.00754728],
       [ 1.44458227,  2.19287089, -0.81114232,  1.00754728],
       [ 1.62527363, -1.85099957,  0.19862659,  1.00754728],
       [ 0.1317978 , -0.1742728 ,  0.88170556,  1.00754728],
       [-0.40548321, -1.85099957, -1.28632769, -0.99250926],
       [ 1.20666029,  2.19287089,  0.40652019,  1.00754728],
       [ 0.80143892, -1.35784464,  0.5847147 , -0.99250926],
       [ 0.54892314, -1.06195168, -0.33595695,  1.00754728],
       [-1.21729949,  0.22025115, -0.66264689,  1.00754728],
       [ 0.39325587,  0.41751312,  0.02043208, -0.99250926],
       [ 0.06326414, -0.56879674,  2.39635892, -0.99250926],
       [ 1.72793104, -0.27290378,  0.22832568, -0.99250926],
       [-1.62004563, -1.55510661, -0.18746152, -0.99250926],
       [-0.5854735 ,  0.71340608, -1.40512403,  1.00754728],
       [ 1.42297771, -1.06195168,  0.5847147 ,  1.00754728],
       [-0.87899501, -1.94963056,  0.3768211 ,  1.00754728],
       [ 1.11436162,  0.41751312,  0.28772385, -0.99250926],
       [-1.32113013,  0.22025115, -0.27655878, -0.99250926],
       [ 1.26512137,  1.50245398, -1.048735  , -0.99250926],
       [-0.72727665,  0.91066806,  1.11929824, -0.99250926],
       [-0.36484947,  1.99560891,  2.21816441,  1.00754728],
       [-1.22197809,  2.0942399 ,  0.40652019, -0.99250926],
       [-0.59049548, -1.35784464, -0.42505421, -0.99250926],
       [ 0.22574186, -1.16058266, -1.01903592, -0.99250926],
       [ 0.65800469,  1.99560891, -0.92993866, -0.99250926],
       [ 0.4378099 ,  0.41751312,  0.31742293, -0.99250926],
       [ 0.48668485,  0.22025115,  0.16892751, -0.99250926],
       [ 0.2630276 ,  2.0942399 ,  1.80237721,  1.00754728],
       [ 0.02082764,  0.81203707, -0.8408414 , -0.99250926],
       [ 0.07542565,  0.31888214, -0.27655878, -0.99250926],
       [-0.09513589,  0.41751312, -0.15776244,  1.00754728],
       [-1.51786037, -0.07564181,  2.27756258, -0.99250926],
       [ 1.21836395, -1.45647562, -0.6329478 , -0.99250926],
       [-1.28528946, -1.25921365, -1.07843409,  1.00754728],
       [ 0.57288846, -1.35784464,  0.43621927,  1.00754728],
       [ 0.86463583, -1.06195168,  0.7926083 , -0.99250926],
       [-1.60819889, -1.45647562, -0.18746152,  1.00754728],
       [ 1.68014348,  1.00929905, -1.07843409,  1.00754728],
       [-1.28809376,  1.00929905,  0.61441379,  1.00754728],
       [-0.51437876,  0.41751312,  1.03020099,  1.00754728],
       [ 1.71216401,  0.6147751 , -0.90023957, -0.99250926],
       [-1.52700296, -0.56879674,  1.50538635,  1.00754728],
       [ 0.62319417,  0.02298918, -0.57354963, -0.99250926],
       [-1.31011324, -0.56879674,  1.95087264, -0.99250926],
       [-0.38857156,  1.40382299, -1.43482311, -0.99250926],
       [-1.46406359,  1.50245398,  1.03020099, -0.99250926],
       [-0.31508745,  0.12162016, -0.81114232,  1.00754728],
       [ 0.44965664,  0.02298918, -0.24685969,  1.00754728],
       [-1.02042617, -0.1742728 , -0.57354963, -0.99250926],
       [ 0.50630064, -0.1742728 , -0.18746152, -0.99250926],
       [ 0.28400262, -0.27290378, -1.31602677, -0.99250926],
       [-0.1164543 , -0.27290378, -0.57354963,  1.00754728],
       [-0.24134581,  0.41751312,  0.10952933,  1.00754728],
       [ 0.66319837,  0.91066806, -0.60324872, -0.99250926],
       [ 1.67567949,  2.0942399 , -1.19723043, -0.99250926],
       [-0.77811175,  1.10793003, -0.12806335,  1.00754728],
       [ 1.78600581,  0.71340608,  1.83207629, -0.99250926],
       [ 1.47949294, -0.66742773,  0.5847147 , -0.99250926],
       [-1.03773843,  0.81203707,  0.3768211 , -0.99250926],
       [-0.86802104,  0.91066806, -0.54385055, -0.99250926],
       [ 1.70855848, -1.16058266, -1.61301763,  1.00754728],
       [-1.38343996,  2.19287089,  0.97080281,  1.00754728],
       [-1.01584772,  0.02298918,  1.26779367, -0.99250926],
       [ 1.75563066,  0.22025115,  1.11929824,  1.00754728],
       [ 1.57109054,  0.41751312, -0.48445238, -0.99250926],
       [-1.04836902, -0.27290378, -0.30625786,  1.00754728],
       [ 0.34697061,  1.00929905, -0.8408414 ,  1.00754728],
       [ 1.50073981,  1.00929905,  1.92117355, -0.99250926],
       [ 1.57538284,  0.02298918,  1.29749276, -0.99250926],
       [ 1.42229094, -0.8646897 ,  2.33696075,  1.00754728],
       [-0.15389743, -1.16058266, -1.61301763, -0.99250926],
       [-0.77997174,  2.19287089, -0.81114232,  1.00754728],
       [-0.15233789, -1.35784464, -1.49422128,  1.00754728],
       [ 0.15923988,  0.41751312,  2.36665983,  1.00754728]])

In [20]:
#Model creation Train set

In [22]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier
param_grid = {'criterion':['gini','entropy'],
              'max_features': ['auto','sqrt','log2'],
              'n_estimators':[10,100]}
grid = GridSearchCV(RandomForestClassifier(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted') 

grid.fit(X_train, Y_train)

Fitting 5 folds for each of 12 candidates, totalling 60 fits

C:\Anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:547: FitFailedWarning:
20 fits failed out of a total of 60.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
8 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Anaconda3\Lib\site-packages\sklearn\base.py", line 1467, in wrapper
    estimator._validate_params()
  File "C:\Anaconda3\Lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "C:\Anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

--------------------------------------------------------------------------------
12 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Anaconda3\Lib\site-packages\sklearn\base.py", line 1467, in wrapper
    estimator._validate_params()
  File "C:\Anaconda3\Lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "C:\Anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:1051: UserWarning: One or more of the test scores are non-finite: [       nan        nan 0.87149815 0.89499144 0.87548641 0.8949812
        nan        nan 0.89007264 0.89881574 0.87543728 0.88754441]
  warnings.warn(
C:\Anaconda3\Lib\site-packages\sklearn\base.py:1474: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

GridSearchCV(estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             scoring='f1_weighted', verbose=3)

In [23]:
# Evaluation Method Presidcting the Test set result

In [24]:
# print best parameter after tuning 
#print(grid.best_params_) 
re=grid.cv_results_
#print(re)

In [25]:
grid_predictions=grid.predict(X_test)

In [26]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test,grid_predictions)

In [27]:
# print classification report 
from sklearn.metrics import classification_report
clf_report = classification_report(Y_test, grid_predictions)

In [28]:
print("The Confusion_Matrix \n:",cm)

The Confusion_Matrix
: [[78  7]
 [ 4 45]]

In [29]:
print("The Report \n:",clf_report)

The Report
:               precision    recall  f1-score   support

           0       0.95      0.92      0.93        85
           1       0.87      0.92      0.89        49

    accuracy                           0.92       134
   macro avg       0.91      0.92      0.91       134
weighted avg       0.92      0.92      0.92       134

In [30]:
from sklearn.metrics import f1_score
f1_macro=f1_score(Y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'criterion': 'entropy', 'max_features': 'sqrt', 'n_estimators': 100}: 0.9183922682195829

In [31]:
from sklearn.metrics import roc_auc_score

roc_auc_score(Y_test,grid.predict_proba(X_test)[:,1])

0.9597839135654261

In [32]:
table=pd.DataFrame.from_dict(re)

In [33]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.003398,4.888702e-04,0.000000,0.000000,gini,auto,10,"{'criterion': 'gini', 'max_features': 'auto', ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
1,0.005597,4.712129e-03,0.000000,0.000000,gini,auto,100,"{'criterion': 'gini', 'max_features': 'auto', ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
2,0.156322,2.225478e-02,0.040175,0.004398,gini,sqrt,10,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.867478,0.850809,0.870362,0.867097,0.901744,0.871498,0.016611,8
3,1.034768,1.175631e-01,0.060301,0.007802,gini,sqrt,100,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.885356,0.850809,0.870362,0.906166,0.962264,0.894991,0.038215,2
4,0.101875,1.469770e-02,0.034534,0.005073,gini,log2,10,"{'criterion': 'gini', 'max_features': 'log2', ...",0.885356,0.811321,0.814409,0.944161,0.922185,0.875486,0.054483,6
5,0.761777,2.176190e-02,0.057440,0.002543,gini,log2,100,"{'criterion': 'gini', 'max_features': 'log2', ...",0.867478,0.868752,0.870362,0.925272,0.943041,0.894981,0.032489,3
6,0.001999,3.873843e-07,0.000000,0.000000,entropy,auto,10,"{'criterion': 'entropy', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
7,0.002398,4.894155e-04,0.000000,0.000000,entropy,auto,100,"{'criterion': 'entropy', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
8,0.089038,8.295389e-03,0.033710,0.003589,entropy,sqrt,10,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.843811,0.868752,0.870362,0.925272,0.942166,0.890073,0.037245,4
9,0.781003,1.048059e-02,0.057846,0.002808,entropy,sqrt,100,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.885356,0.870047,0.870362,0.925272,0.943041,0.898816,0.029914,1
10,0.094074,1.607771e-02,0.031232,0.000606,entropy,log2,10,"{'criterion': 'entropy', 'max_features': 'log2...",0.867478,0.850809,0.870362,0.886792,0.901744,0.875437,0.017416,7
11,0.735128,4.798176e-02,0.049633,0.008900,entropy,log2,100,"{'criterion': 'entropy', 'max_features': 'log2...",0.867478,0.870047,0.870362,0.886792,0.943041,0.887544,0.028581,5

In [ ]:
User_ID_input=int(input("Use ID"))
age_input=float(input("Age:"))
Estimatedsalary_input=float(input("Estimatedsalary:"))
sex_male_input=int(input("Sex Male 1 or 0:"))

In [ ]:
Future_Prediction=grid.predict([[User_ID_input,age_input,Estimatedsalary_input,sex_male_input]])# change the paramter,play with it.
print("Future_Prediction={}".format(Future_Prediction))